  spring:
    datasource:
      username: root
      password: 664243
      url: jdbc:mysql://47.99.165.122:3306/jyweb?useUnicode=true&characterEncoding=utf-8&useSSL=true&autoReconnect=true&failOverReadOnly=false&serverTimezone=CTT
      driver-class-name: com.mysql.jdbc.Driver
      resources:
        chain:
          strategy:
            content:
              enabled: true
              paths: /**
      thymeleaf:
        cache: false
  server:
    servlet:
      context-path: /jy
  #不跨行的话 会讲下面配置 与上面拼在一起 冲突
  #mybatis
  mybatis:
    mapper-locations: classpath:mapper/*Mapper.xml
    type-aliases-package: com.jy.entity
    # spring boot集成mybatis的方式打印sql
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl